<?php if (!empty($this->parameters)): ?>
<?php foreach ($this->parameters as $parameter): ?>
<li>
<?php echo $this->partial('kmb-puppet/group/parameter', ['parameter' => $parameter, 'availableParameters' => $this->availableParameters]) ?>
<?php if ($parameter->hasChildren()): ?>
    <?php if (!$parameter->hasTemplate() || $parameter->getTemplate()->type == \KmbDomain\Model\ParameterType::HASHTABLE): ?>
    <ul style="clear:both">
    <?php echo $this->partial('kmb-puppet/group/parameters', ['parameters' => $parameter->getChildren(), 'availableParameters' => $parameter->getAvailableChildren()]) ?>
    </ul>
    <?php elseif ($parameter->getTemplate()->type == \KmbDomain\Model\ParameterType::EDITABLE_HASHTABLE): ?>
    <ul style="clear:both">
    <?php foreach ($parameter->getChildren() as $child): ?>
        <li>
            <?php echo $this->partial('kmb-puppet/group/parameter', ['parameter' => $child, 'availableParameters' => $this->availableParameters, 'isEditableHashtableKey' => true]) ?>
            <ul style="clear:both">
                <?php echo $this->partial('kmb-puppet/group/parameters', ['parameters' => $child->getChildren(), 'availableParameters' => $child->getAvailableChildren()]) ?>
            </ul>
        </li>
    <?php endforeach ?>
        <form action="#" method="POST">
        <li class="input-group form-inline-editable new-element" style="display: none">
            <input type="text" class="form-control" name="parameter" value="" />
            <div class="input-group-btn">
                <button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-remove"></i></button>
                <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
            </div>
        </li>
        </form>
    </ul>
    <?php endif ?>
<?php elseif ($parameter->hasValues()): ?>
    <ul style="clear:both">
        <?php foreach ($parameter->getValues() as $value): ?>
        <li>
            <span class="tree-item inline-editable">
                <?php if ($parameter->getTemplate()->multiple_values): ?>
                <a href="#"><i class="glyphicon glyphicon-remove red"></i></a>
                <?php endif ?>
                <?php echo $value == '' ? '<i class="lightgrey">' . $this->translate('click to update') . '</i>' : $this->escapeHtml($value) ?>
            </span>
            <div class="input-group form-inline-editable" style="display: none">
                <?php if ($parameter->getTemplate()->type == \KmbDomain\Model\ParameterType::PREDEFINED_LIST): ?>
                    <select class="form-control" name="values[]">
                        <option><?php echo $this->escapeHtml($value) ?></option>
                        <?php foreach ($parameter->getAvailableValues() as $availableValue): ?>
                        <option><?php echo $this->escapeHtml($availableValue) ?></option>
                        <?php endforeach ?>
                    </select>
                <?php elseif ($parameter->getTemplate()->type == \KmbDomain\Model\ParameterType::TEXT): ?>
                    <textarea style="resize:vertical" class="form-control custom-control" name="values[]"><?php echo $this->escapeHtml($value) ?></textarea>
                <?php else: ?>
                    <input type="text" class="form-control" name="values[]" value="<?php echo $this->escapeHtml($value) ?>" />
                <?php endif ?>
                <div class="input-group-<?php echo $parameter->getTemplate()->type == \KmbDomain\Model\ParameterType::TEXT ? 'addon' : 'btn' ?>">
                    <button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-remove"></i></button>
                    <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
                </div>
            </div>
        </li>
        <?php endforeach ?>
        <form action="#" method="POST">
        <li class="new-element input-group form-inline-editable" style="display: none">
            <?php if ($parameter->getTemplate()->type == \KmbDomain\Model\ParameterType::PREDEFINED_LIST): ?>
            <select class="form-control" name="values[]">
                <?php if ($parameter->hasAvailableValues()): ?>
                <?php foreach ($parameter->getAvailableValues() as $availableValue): ?>
                <option><?php echo $this->escapeHtml($availableValue) ?></option>
                <?php endforeach ?>
                <?php else: ?>
                <option value="">--</option>
                <?php endif ?>
            </select>
            <?php elseif ($parameter->getTemplate()->type == \KmbDomain\Model\ParameterType::TEXT): ?>
            <textarea style="resize:vertical" class="form-control custom-control" name="values[]"></textarea>
            <?php else: ?>
            <input type="text" class="form-control" name="values[]" value="" />
            <?php endif ?>
            <div class="input-group-<?php echo $parameter->getTemplate()->type == \KmbDomain\Model\ParameterType::TEXT ? 'addon' : 'btn' ?>">
                <button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-remove"></i></button>
                <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
            </div>
        </li>
        </form>
    </ul>
<?php endif ?>
</li>
<?php endforeach ?>
<form action="#" method="POST">
<li class="input-group form-inline-editable new-element" style="display: none">
    <select class="form-control" name="parameter">
        <?php if (!empty($this->availableParameters)): ?>
            <?php foreach ($this->availableParameters as $parameter): ?>
            <option><?php echo $this->escapeHtml($parameter->name) . ($parameter->required ? '*' : '') ?></option>
            <?php endforeach ?>
        <?php else: ?>
            <option value="">--</option>
        <?php endif ?>
    </select>
    <div class="input-group-btn">
        <button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-remove"></i></button>
        <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
    </div>
</li>
</form>
<?php endif ?>
