<form action="<?php echo $this->url('puppet-group', ['action' => 'update'], [], true) ?>" method="post">
<span class="tree-item inline-editable<?php if (!$this->parameter->hasTemplate()): ?> bg-red<?php endif ?>">
    <a href="#"><i class="glyphicon glyphicon-minus-sign darkgrey"></i></a>
    <?php if (!$this->parameter->hasTemplate()): ?>
    <a href="#"><i class="glyphicon glyphicon-zoom-in darkgrey"></i></a>
    <?php endif ?>
    <?php if ($this->parameter->hasTemplate() && ($this->parameter->getTemplate()->type == \KmbDomain\Model\ParameterType::HASHTABLE || $this->parameter->getTemplate()->type == \KmbDomain\Model\ParameterType::EDITABLE_HASHTABLE || $this->parameter->getTemplate()->multiple_values)): ?>
    <a href="#"><i class="glyphicon glyphicon-plus lightblue"></i></a>
    <?php endif ?>
    <a href="#"><i class="glyphicon glyphicon-remove red"></i></a>
    <span class="blue"><?php echo $this->parameter->getName() ?></span>
    <?php if (!$this->parameter->hasTemplate()): ?>
    <p class="see-more red" style="display: none"><?php echo $this->translate('This parameter does not exists in the class template') ?></p>
    <?php endif ?>
</span>
<div class="input-group form-inline-editable" style="display: none">
    <?php if ($this->isEditableHashtableKey || (!$this->parameter->hasTemplate() && empty($this->availableParameters))): ?>
        <input type="text" class="form-control" name="parameter" value="<?php echo $this->escapeHtml($this->parameter->getName()) ?>" />
    <?php else: ?>
        <select class="form-control" name="parameter">
            <option><?php echo $this->escapeHtml($this->parameter->getName()) ?></option>
            <?php foreach ($this->availableParameters as $sibling): ?>
            <option><?php echo $this->escapeHtml($sibling->name) . ($sibling->required ? '*' : '') ?></option>
            <?php endforeach ?>
        </select>
    <?php endif ?>
    <div class="input-group-btn">
        <button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-remove"></i></button>
        <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
    </div>
</div>
</form>
