<form action="<?php echo $this->url('puppet-parameter', ['action' => 'update', 'id' => $this->parameter->getId(), 'groupId' => $this->group->getId()], ['query' => ['selectedClass' => $this->class->getName()]], true) ?>" method="post">
    <span class="tree-item inline-editable<?php if (!empty($this->error)): ?> bg-red<?php endif ?>">
        <a href="#"><i class="glyphicon glyphicon-minus-sign darkgrey"></i></a>
        <?php if (!empty($this->error)): ?>
        <a href="#"><i class="glyphicon glyphicon-zoom-in darkgrey"></i></a>
        <?php endif ?>
        <?php if (
            $this->type == \KmbDomain\Model\ParameterType::HASHTABLE ||
            $this->type == \KmbDomain\Model\ParameterType::EDITABLE_HASHTABLE ||
            $this->hasMultipleValues): ?>
        <a href="#"><i class="glyphicon glyphicon-plus lightblue"></i></a>
        <?php endif ?>
        <a href="#"><i class="glyphicon glyphicon-remove red"></i></a>
        <span class="<?php if ($this->isEditableHashtableKey): ?>darkgrey<?php else: ?>blue<?php endif ?>"><?php echo $this->parameter->getName() ?></span>
        <?php if (!empty($this->error)): ?>
        <p class="see-more red" style="display: none"><?php echo $this->error ?></p>
        <?php endif ?>
    </span>
    <div class="form-inline-editable" style="display: none">
        <div class="input-group">
            <?php if ($this->isEditableHashtableKey || (!$this->parameter->hasTemplate() && empty($this->availableParameters))): ?>
                <input type="text" class="form-control" name="name" value="<?php echo $this->escapeHtml($this->parameter->getName()) ?>" />
            <?php else: ?>
                <select class="form-control" name="name">
                    <option><?php echo $this->escapeHtml($this->parameter->getName()) ?></option>
                    <?php foreach ($this->availableParameters as $sibling): ?>
                        <option><?php echo $this->escapeHtml($sibling->name) . ($sibling->required ? '*' : '') ?></option>
                    <?php endforeach ?>
                </select>
            <?php endif ?>
            <div class="input-group-btn">
                <button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-remove"></i></button>
                <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
            </div>
        </div>
    </div>
    <?php if ($this->parameter->hasValues()): ?>
        <?php echo $this->partial('kmb-puppet/group/values', [
            'parameter' => $this->parameter,
            'type' => $this->parameter->hasTemplate() ? $this->parameter->getTemplate()->type : null,
            'class' => $this->class,
            'group' => $this->group,
        ]) ?>
    <?php endif ?>
</form>
