<ul style="clear:both">
<?php if (!empty($this->parameters)): ?>
<?php foreach ($this->parameters as $parameter): ?>
    <li class="tree-level" id="parameter<?php echo $parameter->getId() ?>">
        <?php echo $this->partial('kmb-puppet/group/parameter', [
            'environment' => $this->environment,
            'group' => $this->group,
            'class' => $this->class,
            'parameter' => $parameter,
            'type' => $parameter->hasTemplate() ? $parameter->getTemplate()->type : null,
            'hasMultipleValues' => $parameter->hasTemplate() ? $parameter->getTemplate()->multiple_values : null,
            'availableParameters' => $this->availableParameters,
            'error' => isset($this->errors[$parameter->getName()]['global']) ? $this->errors[$parameter->getName()]['global'] : '',
        ]) ?>
        <?php if ($parameter->hasTemplate() && $parameter->getTemplate()->type == \KmbDomain\Model\GroupParameterType::EDITABLE_HASHTABLE): ?>
        <ul style="clear:both">
            <?php foreach ($parameter->getChildren() as $child): ?>
            <li class="tree-level" id="parameter<?php echo $child->getId() ?>">
                <?php echo $this->partial('kmb-puppet/group/parameter', [
                    'environment' => $this->environment,
                    'group' => $this->group,
                    'class' => $this->class,
                    'parameter' => $child,
                    'type' => $child->hasTemplate() ? $child->getTemplate()->type : null,
                    'hasMultipleValues' => $child->hasTemplate() ? $child->getTemplate()->multiple_values : null,
                    'availableParameters' => $this->availableParameters,
                    'isEditableHashtableKey' => true,
                ]) ?>
                <?php echo $this->partial('kmb-puppet/group/parameters', [
                    'environment' => $this->environment,
                    'group' => $this->group,
                    'class' => $this->class,
                    'parameters' => $child->getChildren(),
                    'parent' => $child,
                    'availableParameters' => $child->getAvailableChildren(),
                    'errors' => isset($this->errors[$child->getName()]['parameters']) ? $this->errors[$child->getName()]['parameters'] : [],
                ]) ?>
            </li>
            <?php endforeach ?>
            <li class="new-element form-inline-editable" style="display: none">
                <?php echo $this->partial('kmb-puppet/group/parameter-new', [
                    'environment' => $this->environment,
                    'group' => $this->group,
                    'class' => $this->class,
                    'parent' => $parameter,
                    'isEditableHashtableKey' => true,
                    'availableParameters' => $parameter->getAvailableChildren(),
                ]) ?>
            </li>
        </ul>
        <?php elseif (!$parameter->hasTemplate() || $parameter->getTemplate()->type == \KmbDomain\Model\GroupParameterType::HASHTABLE): ?>
            <?php echo $this->partial('kmb-puppet/group/parameters', [
                'environment' => $this->environment,
                'group' => $this->group,
                'class' => $this->class,
                'parameters' => $parameter->getChildren(),
                'parent' => $parameter,
                'availableParameters' => $parameter->getAvailableChildren(),
                'errors' => isset($this->errors[$parameter->getName()]['parameters']) ? $this->errors[$parameter->getName()]['parameters'] : [],
            ]) ?>
        <?php endif ?>
    </li>
<?php endforeach ?>
<?php endif ?>
    <li class="new-element form-inline-editable" style="display: none">
        <?php echo $this->partial('kmb-puppet/group/parameter-new', [
            'environment' => $this->environment,
            'group' => $this->group,
            'class' => $this->class,
            'parent' => $this->parent,
            'availableParameters' => $this->availableParameters,
        ]) ?>
    </li>
</ul>
