<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.puppet.js'); ?>
<form action="<?php echo $this->url('puppet-group', ['action' => 'update'], ['id' => $this->group->getId()], true) ?>" method="post">
    <div class="row" style="margin-bottom: 8px">
        <div class="col-md-3">
            <div><?php echo $this->translate('Detailed informations on group') ?></div>
            <div><input type="text" tabindex="100" class="form-control editable" data-target="#actions" name="name" id="group-name" value="<?php echo $this->escapeHtml($this->group->getName()) ?>" /></div>
        </div>
        <div id="actions" class="editable-actions pull-right" style="display: none">
            <div>&nbsp;</div>
            <button class="btn btn-default" tabindex="110" type="reset"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('Cancel') ?></button>
            <a href="#" class="btn btn-warning" tabindex="111" data-href="<?php echo $this->url('puppet-group', ['action' => 'servers'], ['id' => $this->group->getId()], true) ?>" data-toggle="modal" data-target="#group-servers" data-current="true" data-count="<?php echo $this->serversCount ?>"><i class="glyphicon glyphicon-search"></i> <?php echo $this->translate('Preview') ?></a>
            <button class="btn btn-primary" tabindex="112" type="submit"><i class="glyphicon glyphicon-ok"></i> <?php echo $this->translate('Save') ?></button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 info-bar pull-left">
            <div>&nbsp;</div>
            <div><a tabindex="900" href="<?php echo $this->back ?>" class="btn btn-info"><i class="glyphicon glyphicon-chevron-left"></i> <?php echo $this->translate('back') ?></a></div>
        </div>
        <div class="col-md-3 info-bar pull-right">
            <div class="yellow"><?php echo $this->translate('exclude') ?></div>
                <input type="text" tabindex="103" class="form-control editable" data-target="#actions" name="exclude" id="group-exclude-pattern" value="<?php echo $this->escapeHtml($this->group->getExcludePattern()) ?>" />
        </div>
        <div class="col-md-3 info-bar pull-right">
            <div class="yellow"><?php echo $this->translate('include') ?></div>
                <input type="text" tabindex="102" class="form-control editable" data-target="#actions" name="include" id="group-include-pattern" value="<?php echo $this->escapeHtml($this->group->getIncludePattern()) ?>" />
        </div>
        <div class="col-md-2 info-bar pull-right">
            <div class="yellow"><?php echo $this->translate('servers') ?></div>
            <div>
                <a href="#" tabindex="101" class="btn btn-success" id="servers-count" data-href="<?php echo $this->url('puppet-group', ['action' => 'servers'], ['id' => $this->group->getId()], true) ?>" data-toggle="modal" data-target="#group-servers" data-count="<?php echo $this->serversCount ?>"><?php echo $this->serversCount ?></a>
            </div>
        </div>
    </div>
</form>
<div id="group-servers" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="groupUsersLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h1 class="modal-title" id="groupUsersLabel"><?php echo $this->translate('Servers list') ?></h1>
                <h4 class="lightgrey"><?php echo $this->translate('Servers count') ?>&nbsp;: <span id="modal-servers-count"></span></h4>
            </div>
            <div class="modal-body" style="min-height: 420px">
                <div class="input-group" style="margin-bottom: 5px">
                    <input type="text" id="servers-filter" class="form-control" placeholder="<?php echo $this->translate('Filter list') ?>" />
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
                <div class="list-group">
                </div>
            </div>
        </div>
    </div>
</div>
<hr/>
<?php echo $this->customGroups()->render($this->group->getType());
