<div class="row">
    <div class="row">
        <div class="col-md-3">
            <div><?php echo $this->translate('Detailed informations on group') ?></div>
            <form class="editable" action="<?php echo $this->url('puppet-group', ['action' => 'update'], ['id' => $group->getId()], true) ?>" method="post">
                <input type="text" class="form-control" name="name" id="group-name" value="<?php echo $this->escapeHtml($this->group->getName()) ?>" />
                <div class="input-group-btn" style="display: none">
                    <button class="btn btn-warning" type="reset"><i class="glyphicon glyphicon-remove-sign"></i></button>
                    <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 info-bar pull-left">
            <div class="grey"><span class="glyphicon glyphicon-chevron-left"></span></div>
            <div><a href="<?php echo $this->url('puppet', ['controller' => 'groups', 'action' => 'index'], [], true) ?>" class="btn btn-info"><?php echo $this->translate('back') ?></a></div>
        </div>
        <div class="col-md-3 info-bar pull-right">
            <div class="yellow"><?php echo $this->translate('exclude') ?></div>
            <form class="editable" action="<?php echo $this->url('puppet-group', ['action' => 'update'], ['id' => $group->getId()], true) ?>" method="post">
                <input type="text" class="form-control" name="exclude" id="group-exclude-pattern" value="<?php echo $this->escapeHtml($this->group->getExcludePattern()) ?>" />
                <div class="input-group-btn" style="display: none">
                    <a href="#" class="btn btn-default" data-href="<?php echo $this->url('puppet-group', ['action' => 'servers'], ['id' => $group->getId()], true) ?>" data-toggle="modal" data-target="#group-servers" data-count="<?php echo $this->serversCount ?>"><i class="glyphicon glyphicon-question-sign darkgrey"></i></a>
                    <button class="btn btn-warning" type="reset"><i class="glyphicon glyphicon-remove-sign"></i></button>
                    <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
                </div>
            </form>
        </div>
        <div class="col-md-3 info-bar pull-right">
            <div class="yellow"><?php echo $this->translate('include') ?></div>
            <form class="editable" action="<?php echo $this->url('puppet-group', ['action' => 'update'], ['id' => $group->getId()], true) ?>" method="post">
                <input type="text" class="form-control" name="include" id="group-include-pattern" value="<?php echo $this->escapeHtml($this->group->getIncludePattern()) ?>" />
                <div class="input-group-btn" style="display: none">
                    <a href="#" class="btn btn-default" data-href="<?php echo $this->url('puppet-group', ['action' => 'servers'], ['id' => $group->getId()], true) ?>" data-toggle="modal" data-target="#group-servers" data-count="<?php echo $this->serversCount ?>"><i class="glyphicon glyphicon-question-sign darkgrey"></i></a>
                    <button class="btn btn-warning reset" type="reset"><i class="glyphicon glyphicon-remove-sign"></i></button>
                    <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
                </div>
            </form>
        </div>
        <div class="col-md-2 info-bar pull-right">
            <div class="yellow"><?php echo $this->translate('servers') ?></div>
            <div>
                <a href="#" class="btn btn-success" id="servers-count" data-href="<?php echo $this->url('puppet-group', ['action' => 'servers'], ['id' => $group->getId()], true) ?>" data-toggle="modal" data-target="#group-servers" data-count="<?php echo $this->serversCount ?>"><?php echo $this->serversCount ?></a>
            </div>
        </div>
    </div>
    <div id="group-servers" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="groupUsersLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="groupUsersLabel"><?php echo $this->translate('Servers list') ?></h1>
                    <h4 class="lightgrey"><?php echo $this->translate('Servers count') ?>&nbsp;: <span id="modal-servers-count"></span></h4>
                </div>
                <div class="modal-body" style="min-height: 420px">
                    <div class="input-group" style="margin-bottom: 5px">
                        <input type="text" id="servers-filter" class="form-control" placeholder="<?php echo $this->translate('Filter list') ?>" />
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                    <div class="list-group">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr/>
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span>
                    <?php echo sprintf($this->translate('Classes of group %s'), $this->group->getName()) ?>
                </span>
            </div>
            <div class="panel-body">
                <?php if ($this->group->hasClasses()): ?>
                <table class="table table-striped" id="classes">
                    <tbody>
                    <?php foreach ($this->group->getClasses() as $class): ?>
                        <tr>
                            <td class="class-name" style="width: 90%">
                                <span class="glyphicon glyphicon-search"></span>
                                <a href="#"><?php echo $class->getName() ?></a>
                            </td>
                            <td class="text-right">
                            <?php if (isset($this->classesErrors[$class->getName()])): ?>
                                <span class="label label-uniform label-danger">
                                    <?php echo $this->translate('Error') ?>
                                    <span class="badge alert-danger" data-rel="tooltip" data-placement="top" data-original-title="errors"><?php echo $this->classesErrors[$class->getName()] ?></span>
                                </span>
                            <?php endif ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <?php else: ?>
                <h4><?php echo $this->translate('No classes available !') ?></h4>
                <?php endif ?>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <?php if (isset($this->error)): ?>
        <ul class="flash">
            <li class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <?php echo $this->error ?>
            </li>
        </ul>
        <?php endif ?>
        <?php echo $this->flashMessenger()->render('success', ['alert', 'alert-success']) ?>
        <?php echo $this->flashMessenger()->render('error', ['alert', 'alert-danger']) ?>
        <ul class="nav nav-pills pull-right">
            <li><a href="#"><?php echo $this->translate('edit') ?></a></li>
        </ul>
        <h1><?php echo $this->translate('Description') ?></h1>
        <blockquote>
            <p><?php echo $this->translate('No description yet provided for this group.') ?></p>
        </blockquote>
    </div>
</div>
