<form class="values-form" action="<?php echo $this->url('puppet-group-parameter', ['action' => 'update', 'id' => $this->parameter->getId(), 'groupId' => $this->group->getId()], ['query' => ['selectedClass' => $this->class->getName()]], true) ?>" method="post">
    <ul style="clear:both">
        <?php if ($this->parameter->hasValues()): ?>
        <?php foreach ($this->parameter->getValues() as $value): ?>
        <li class="tree-level">
            <?php echo $this->partial('kmb-puppet/group/value', [
                'parameter' => $this->parameter,
                'value' => $value,
                'type' => $this->type,
                'hasMultipleValues' => $this->parameter->hasTemplate() && $this->parameter->getTemplate()->multiple_values,
                'availableValues' => $this->parameter->getAvailableValues(),
            ]) ?>
        </li>
        <?php endforeach ?>
        <?php endif ?>
        <li class="new-element form-inline-editable" style="display: none">
            <?php echo $this->partial('kmb-puppet/group/value-new', [
                'type' => $this->type,
                'availableValues' => $this->parameter->getAvailableValues(),
            ]) ?>
        </li>
    </ul>
</form>
