<?php if ($this->isGranted('manageEnv', $this->environment)): ?>
<span class="tree-item inline-editable"<?php if ($this->hasMultipleValues): ?> style="padding-left: 26px"<?php endif ?>>
    <?php if ($this->hasMultipleValues): ?>
        <a href="#" class="remove-value" style="position: absolute; margin-left: -18px" data-toggle="modal" data-target="#confirm-remove-value" data-confirm-text="<?php echo sprintf($this->translate('You are about to remove a value of <strong>%s</strong> parameter.'), $this->parameter->getName()) ?>"><i class="glyphicon glyphicon-remove red"></i></a>
    <?php endif ?>
    <?php if ($this->type == \KmbDomain\Model\GroupParameterType::BOOLEAN): ?>
        <span class="inline-editable-clickable darkgrey"><?php echo $this->printBoolean($this->value) ?></span>
    <?php elseif (empty($this->value)): ?>
        <i class="inline-editable-clickable lightgrey"><?php echo $this->translate('click to update') ?></i>
    <?php elseif ($this->type == \KmbDomain\Model\GroupParameterType::PASSWORD): ?>
        <span class="inline-editable-clickable darkgrey"><?php echo $this->truncate(str_repeat('*', strlen($this->value)), 32) ?></span>
    <?php else: ?>
        <span class="inline-editable-clickable darkgrey" style="white-space: pre-wrap"><?php echo $this->escapeHtml($this->value) ?></span>
    <?php endif ?>
</span>
<?php else: ?>
<span class="tree-item">
    <?php if ($this->type == \KmbDomain\Model\GroupParameterType::BOOLEAN): ?>
        <span class="darkgrey"><?php echo $this->printBoolean($this->value) ?></span>
    <?php elseif (empty($this->value)): ?>
        <i class="lightgrey"><?php echo $this->translate('no value') ?></i>
    <?php elseif ($this->type == \KmbDomain\Model\GroupParameterType::PASSWORD): ?>
        <span class="darkgrey"><?php echo $this->truncate(str_repeat('*', strlen($this->value)), 32) ?></span>
    <?php else: ?>
        <span class="darkgrey" style="white-space: pre-wrap"><?php echo $this->escapeHtml($this->value) ?></span>
    <?php endif ?>
</span>
<?php endif ?>
<div class="form-inline-editable" style="display: none">
    <div class="input-group">
        <?php if ($this->type == \KmbDomain\Model\GroupParameterType::PREDEFINED_LIST): ?>
            <select class="form-control" name="values[]">
                <option><?php echo $this->escapeHtml($this->value) ?></option>
                <?php foreach ($this->availableValues as $availableValue): ?>
                    <option><?php echo $this->escapeHtml($availableValue) ?></option>
                <?php endforeach ?>
            </select>
        <?php elseif ($this->type == \KmbDomain\Model\GroupParameterType::BOOLEAN): ?>
            <select class="form-control" name="values[]">
                <option value="1"><?php echo $this->printBoolean(true) ?></option>
                <option value="0"<?php if (!$this->value): ?> selected="selected"<?php endif ?>><?php echo $this->printBoolean(false) ?></option>
            </select>
        <?php elseif ($this->type == \KmbDomain\Model\GroupParameterType::TEXT): ?>
            <textarea style="resize:vertical" class="form-control custom-control" name="values[]"><?php echo $this->escapeHtml($this->value) ?></textarea>
        <?php elseif ($this->type == \KmbDomain\Model\GroupParameterType::PASSWORD): ?>
            <input type="password" class="form-control" name="values[]" value="<?php echo $this->escapeHtml($this->value) ?>" />
        <?php else: ?>
            <input type="text" class="form-control" name="values[]" value="<?php echo $this->escapeHtml($this->value) ?>" />
        <?php endif ?>
        <div class="input-group-<?php echo ($this->type == \KmbDomain\Model\GroupParameterType::TEXT ? 'addon' : 'btn') ?>">
            <button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-remove"></i></button>
            <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
        </div>
    </div>
</div>
