<div class="input-group <?php echo '#' . $this->type . '#' ?>">
    <?php if ($this->type == \KmbDomain\Model\GroupParameterType::PREDEFINED_LIST): ?>
        <select class="form-control" name="values[]" disabled="disabled">
            <?php if (empty($this->availableValues)): ?>
                <option value="">--</option>
            <?php else: ?>
                <?php foreach ($this->availableValues as $availableValue): ?>
                    <option><?php echo $this->escapeHtml($availableValue) ?></option>
                <?php endforeach ?>
            <?php endif ?>
        </select>
    <?php elseif ($this->type == \KmbDomain\Model\GroupParameterType::TEXT): ?>
        <textarea style="resize:vertical" disabled="disabled" class="form-control custom-control" name="values[]"></textarea>
    <?php elseif ($this->type == \KmbDomain\Model\GroupParameterType::PASSWORD): ?>
        <input type="password" disabled="disabled" class="form-control" name="values[]" value="" />
    <?php else: ?>
        <input type="text" disabled="disabled" class="form-control" name="values[]" value="" />
    <?php endif ?>
    <div class="input-group-<?php echo $this->type == \KmbDomain\Model\GroupParameterType::TEXT ? 'addon' : 'btn' ?>">
        <button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-remove"></i></button>
        <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
    </div>
</div>
