<span class="tree-item inline-editable">
    <?php if ($this->hasMultipleValues): ?>
        <a href="#" class="remove-value" data-toggle="modal" data-target="#confirm-remove-value" data-confirm-text="<?php echo sprintf($this->translate('You are about to remove a value of <strong>%s</strong> parameter.'), $this->parameter->getName()) ?>"><i class="glyphicon glyphicon-remove red"></i></a>
    <?php endif ?>
    <?php if (empty($this->value)): ?>
        <i class="inline-editable-clickable lightgrey"><?php echo $this->translate('click to update') ?></i>
    <?php else: ?>
        <span class="inline-editable-clickable darkgrey"><?php echo $this->escapeHtml($this->value) ?></span>
    <?php endif ?>
</span>
<div class="form-inline-editable" style="display: none">
    <div class="input-group">
        <?php if ($this->type == \KmbDomain\Model\ParameterType::PREDEFINED_LIST): ?>
            <select class="form-control" name="values[]">
                <option><?php echo $this->escapeHtml($this->value) ?></option>
                <?php foreach ($this->availableValues as $availableValue): ?>
                    <option><?php echo $this->escapeHtml($availableValue) ?></option>
                <?php endforeach ?>
            </select>
        <?php elseif ($this->type == \KmbDomain\Model\ParameterType::TEXT): ?>
            <textarea style="resize:vertical" class="form-control custom-control" name="values[]"><?php echo $this->escapeHtml($this->value) ?></textarea>
        <?php else: ?>
            <input type="text" class="form-control" name="values[]" value="<?php echo $this->escapeHtml($this->value) ?>" />
        <?php endif ?>
        <div class="input-group-<?php echo ($this->type == \KmbDomain\Model\ParameterType::TEXT ? 'addon' : 'btn') ?>">
            <button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-remove"></i></button>
            <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-ok"></i></button>
        </div>
    </div>
</div>
