<div class="row">
    <div class="col-sm-8">
        <form action="<?php echo $this->url('puppet', ['controller' => 'revisions', 'action' => 'diff'], [], true) ?>" method="get">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span><?php echo $this->translate('Changes history') ?></span>
                <span class="pull-right">
                    <a class="btn btn-info btn-xs">
                        <span class="glyphicon glyphicon-import"></span>
                        <?php echo $this->translate('Import version') ?>
                    </a>
                    <button class="btn btn-info btn-xs">
                        <span class="glyphicon glyphicon-transfer"></span>
                        <?php echo $this->translate('Compare selected versions') ?>
                    </button>
                </span>
            </div>
            <div class="panel-body">
                <?php if (isset($this->revisions)): ?>
                <table class="table table-striped">
                    <tbody>
                    <?php if (isset($this->currentRevision)): ?>
                        <tr>
                            <?php if ($this->currentRevision->hasLogs()): ?>
                            <td style="background-color: #fffdde">
                                <input type="radio" name="from" value="<?php echo $this->currentRevision->getId() ?>" />
                                <input type="radio" name="to" checked="checked" value="<?php echo $this->currentRevision->getId() ?>" />
                                <span><?php echo $this->translate('Current changes') ?></span>
                                <div class="pull-right">
                                    <?php if ($this->isGranted('manageEnv', $this->environment)): ?>
                                    <a class="red" href="#" data-href="<?php echo $this->url('puppet-revision', ['action' => 'remove', 'id' => $this->currentRevision->getId()], [], true) ?>" data-toggle="modal" data-target="#confirm-remove" data-confirm-param1="<?php echo $this->translate("You are about to remove all current changes.") ?>"><i class="glyphicon glyphicon-remove"></i></a>
                                    <a class="green" href="#"data-href="<?php echo $this->url('puppet-revision', ['action' => 'release', 'id' => $this->currentRevision->getId()], [], true) ?>" data-toggle="modal" data-target="#release" data-release-warning="<?php echo $this->translate('Warning ! You are about to save current changes, it will be immediately accessible by Puppet.') ?>"><i class="glyphicon glyphicon-ok"></i></a>
                                    <a class="grey" href="#"><i class="glyphicon glyphicon-export"></i></a>
                                    <?php endif ?>
                                    <a class="grey" href="#"><i class="glyphicon glyphicon-search"></i></a>
                                </div>
                                <br />
                                <span class="comment"><?php echo $this->dateFormat($this->currentRevision->getLastLog()->getCreatedAt(), IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT); ?></span>
                                <span class="comment"><?php echo $this->currentRevision->getLastLog()->getCreatedBy(); ?></span>
                                <span class="label label-warning"><?php echo $this->translate('current revision') ?></span>
                            </td>
                            <?php else: ?>
                            <td style="background-color: #fffdde">
                                <input type="radio" name="from" value="<?php echo $this->currentRevision->getId() ?>" />
                                <input type="radio" name="to" checked="checked" value="<?php echo $this->currentRevision->getId() ?>" />
                                <span><?php echo $this->translate('No current changes') ?></span>
                                <span class="label label-warning"><?php echo $this->translate('current revision') ?></span>
                            </td>
                            <?php endif ?>
                        </tr>
                    <?php endif ?>
                    <?php foreach ($this->revisions as $index => $revision): ?>
                        <tr>
                            <td>
                                <input type="radio" name="from" value="<?php echo $revision->getId() ?>" <?php if ($index == 0) { echo 'checked="checked" '; } ?>/>
                                <input type="radio" name="to" value="<?php echo $revision->getId() ?>" />
                                <span><?php echo $this->escapeHtml($revision->getComment()); ?></span>
                                <div class="pull-right">
                                    <?php if ($this->isGranted('manageEnv', $this->environment)): ?>
                                    <?php if ($revision->getId() != $this->lastReleasedRevision->getId()): ?>
                                    <a class="red" href="#" data-href="<?php echo $this->url('puppet-revision', ['action' => 'remove', 'id' => $revision->getId()], [], true) ?>" data-toggle="modal" data-target="#confirm-remove" data-confirm-param1="<?php echo $this->translate("You are about to remove a revision.") ?>"><i class="glyphicon glyphicon-remove"></i></a>
                                    <a class="blue" href="#" data-href="<?php echo $this->url('puppet-revision', ['action' => 'release', 'id' => $revision->getId()], [], true) ?>" data-toggle="modal" data-target="#release" data-release-warning="<?php echo $this->translate('Warning ! You are about to restore a revision. It will be immediately accessible by Puppet, all current changes will be definitively lost.') ?>"><i class="glyphicon glyphicon-repeat"></i></a>
                                    <?php endif ?>
                                    <a class="grey" href="#"><i class="glyphicon glyphicon-export"></i></a>
                                    <?php endif ?>
                                    <a class="grey" href="#"><i class="glyphicon glyphicon-search"></i></a>
                                </div>
                                <br />
                                <span class="comment"><?php echo $this->dateFormat($revision->getReleasedAt(), IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT); ?></span>
                                <span class="comment"><?php echo $revision->getReleasedBy(); ?></span>
                                <?php if ($revision->getId() == $this->lastReleasedRevision->getId()): ?>
                                <span class="label label-success"><?php echo $this->translate('active revision') ?></span>
                                <?php endif ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif ?>
            </div>
        </div>
        </form>
    </div>
    <div id="release" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="releaseLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="releaseLabel"><?php echo $this->translate('Activate a revision') ?></h1>
                </div>
                <form role="form" action="#" method="post">
                    <div class="modal-body">
                        <blockquote style="margin-top: 16px">
                            <p class="release-warning"></p>
                        </blockquote>
                        <div class="form-group">
                            <input type="text" class="form-control" id="comment" name="comment" placeholder="<?php echo $this->translate('Enter a comment') ?>" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                        <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save') ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div id="confirm-remove" class="modal fade confirm" tabindex="-1" role="dialog" aria-labelledby="confirmRemoveLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="confirmRemoveLabel"><?php echo $this->translate('Confirm Remove') ?></h1>
                </div>
                <div class="modal-body">
                    <blockquote>
                        <p class="confirm-param1"></p>
                        <p><?php echo $this->translate("Don't forget to consult logs before (by clicking on icon&nbsp;<i class=\"glyphicon glyphicon-search lightgrey\"></i>) to be aware of what you are removing.") ?></p>
                        <p><?php echo $this->translate('Do you want to proceed ?') ?></p>
                    </blockquote>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                    <a href="#" class="btn btn-danger danger"><?php echo $this->translate('Remove') ?></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <?php if (isset($this->error)): ?>
        <ul class="flash">
            <li class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <?php echo $this->error ?>
            </li>
        </ul>
        <?php endif ?>
        <?php echo $this->flashMessenger()->render('success', ['alert', 'alert-success']) ?>
        <?php echo $this->flashMessenger()->render('error', ['alert', 'alert-danger']) ?>
        <h1><?php echo $this->translate('Help') ?></h1>
        <blockquote>
            <p><?php echo $this->translate('Click on <i class="glyphicon glyphicon-ok green"></i> to save current changes.') ?></p>
            <p><?php echo $this->translate('You can restore a revision by clicking on <i class="glyphicon glyphicon-repeat blue"></i>, or remove it by clicking on <i class="glyphicon glyphicon-remove red"></i>.') ?></p>
            <p><?php echo $this->translate('Click on <i class="glyphicon glyphicon-export grey"></i> to export a revision.') ?></p>
            <p><?php echo $this->translate('View all logs of a revision by clicking on <i class="glyphicon glyphicon-search grey"></i>.') ?></p>
        </blockquote>
    </div>
</div>
