<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.puppet.js'); ?>
<div class="row">
    <div class="col-sm-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th"></span><span class="panel-break"></span>
                <span>
<?php if(isset($this->environment)): ?>
                    <?php echo sprintf($this->translate('Modules of %s environment'), $this->environment->getNormalizedName()); ?>
<?php endif ?>
                </span>
                <div class="pull-right">
                    <?php echo $this->widget('puppetModulesPanelHeading')->render($this->viewModel()->getCurrent()); ?>
                </div>
            </div>
            <div class="panel-body">
                <?php if (empty($this->puppetModules)): ?>
                    <?php echo $this->translate('No modules') ?>
                <?php else: ?>
                <table class="table table-striped" id="modules">
                    <tbody>
                    <?php foreach ($this->puppetModules as $puppetModule): ?>
                    <tr>
                        <td class="module-name" style="width: 100%">
                            <?php echo $this->widget('puppetModuleRowLeft')->render(['puppetModule' => $puppetModule]); ?>
                            <a href="<?php echo $this->url('puppet-module', ['action' => 'show', 'moduleName' => $puppetModule->getName()], ['query' => ['back' => $this->url('puppet', ['controller' => 'modules', 'action' => 'index'], [], true)]], true) ?>" title="<?php echo $this->translate('View module') ?>"><span class="glyphicon glyphicon-search darkgrey" style="margin-right: 6px"></span><?php echo $puppetModule->getName() ?></a>
                        </td>
                        <td>
                            <span class="label <?php echo $this->puppetModuleLabelClass($puppetModule) ?>"><?php echo $this->formatModuleVersion($puppetModule->getVersion()) ?></span>
                            <?php echo $this->widget('puppetModuleRowRight')->render(['puppetModule' => $puppetModule]); ?>
                        </td>
                    </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <?php endif ?>
            </div>
        </div>
        <?php if (!empty($this->inheritedPuppetModules)): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-signal"></span><span class="panel-break"></span>
                <span>
                    <?php echo $this->translate('Inherited modules') ?>
                </span>
                <?php if ($this->environment->hasParent()): ?>
                <div class="pull-right">
                    <a class="btn btn-xs btn-info" href="<?php echo $this->url('puppet', ['controller' => 'modules', 'action' => 'index', 'envId' => $this->environment->getParent()->getId()], [], true) ?>" title="<?php echo sprintf($this->translate('View modules list of %s environment'), $this->environment->getParent()->getNormalizedName()); ?>">
                        <span class="glyphicon glyphicon-search"></span>
                        <?php echo $this->translate("View parent's modules") ?>
                    </a>
                </div>
                <?php endif ?>
            </div>
            <div class="panel-body">
                <table class="table table-striped" id="modules">
                    <tbody>
                    <?php if (isset($this->inheritedPuppetModules)): ?>
                        <?php foreach ($this->inheritedPuppetModules as $puppetModule): ?>
                            <tr>
                                <td class="module-name" style="width: 100%">
                                    <?php echo $puppetModule->getName() ?>
                                </td>
                                <td>
                                    <span class="label <?php echo $this->puppetModuleLabelClass($puppetModule) ?>"><?php echo $this->formatModuleVersion($puppetModule->getVersion()) ?></span>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    <?php endif ?>
                    </tbody>
                </table>
            </div>
        </div>
        <?php endif ?>
    </div>
    <div class="col-sm-5">
        <h1><?php echo $this->translate('Help') ?></h1>
        <?php if (isset($this->environment)): ?>
        <blockquote>
            <p><?php echo sprintf($this->translate("Here is the list of installed modules on environment <strong>%s</strong>."), $this->environment->getNormalizedName()) ?></p>
            <p><?php echo $this->translate('When version of a module is red <span class="label label-danger">1.0.0</span>, it means that at least one of its classes is in error.') ?></p>
            <p><?php echo $this->translate('<strong>Note</strong> : The list of modules is refreshed every 5 minutes, but you can clear the cache manually by clicking on your name in the top right of the page.') ?></p>
        </blockquote>
        <?php endif ?>
    </div>
</div>
