<div class="row">
    <div class="col-sm-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span>
                    <?php echo $this->translate('Modules') ?>
                    <a class="btn btn-info btn-xs pull-right<?php if (!isset($this->modules)): ?> disabled<?php endif ?>">
                        <span class="glyphicon glyphicon-plus-sign"></span>
                        <?php echo $this->translate('Add a module') ?>
                    </a>
                </span>
            </div>
            <div class="panel-body">
                <table class="table table-striped" id="modules">
                    <tbody>
                    <?php if (isset($this->modules)): ?>
                    <?php foreach ($this->modules as $module): ?>
                    <tr>
                        <td class="module-name" style="width: 100%">
                            <span class="glyphicon glyphicon-search"></span>
                            <a href="<?php echo $this->url('puppet-module', ['action' => 'show', 'name' => $module->getName()], ['query' => ['back' => $this->url('puppet', ['controller' => 'modules', 'action' => 'index'], [], true)]], true) ?>"><?php echo $module->getName() ?></a>
                        </td>
                        <td>
                            <span class="label <?php echo $this->moduleLabelClass($module) ?>"><?php echo $module->getVersion() ?></span>
                        </td>
                    </tr>
                    <?php endforeach ?>
                    <?php endif ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-5">
        <?php if (isset($this->error)): ?>
        <ul class="flash">
            <li class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <?php echo $this->error ?>
            </li>
        </ul>
        <?php endif ?>
        <?php echo $this->flashMessenger()->render('success', ['alert', 'alert-success']) ?>
        <?php echo $this->flashMessenger()->render('error', ['alert', 'alert-danger']) ?>
        <?php if (isset($this->environment)): ?>
        <h1><?php echo $this->translate('Help') ?></h1>
        <blockquote>
            <p><?php echo sprintf($this->translate("Here is the list of installed modules on environment <strong>%s</strong>."), $this->environment->getNormalizedName()) ?></p>
            <p><?php echo $this->translate('When version of a module is red <span class="label label-danger">1.0.0</span>, it means that at least one of its classes is in error.') ?></p>
            <p><?php echo $this->translate('<strong>Note</strong> : The list of modules is refreshed every 5 minutes, but you can clear the cache manually by clicking on your name in the top right of the page.') ?></p>
        </blockquote>
        <?php endif ?>
    </div>
</div>
