<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.puppet.js'); ?>
<div class="row">
    <div class="col-sm-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th"></span><span class="panel-break"></span>
                <span>
                    <?php echo $this->translate('Modules') ?>
                </span>
                <div class="pull-right">
                    <?php echo $this->widget()->render('puppetModulesPanelHeading', ['puppetModules' => $this->puppetModules]); ?>
                </div>
            </div>
            <div class="panel-body">
                <h4>Environment STABLE</h4>
                <table class="table table-striped" id="modules">
                    <tbody>
                    <?php if (isset($this->puppetModules)): ?>
                    <?php foreach ($this->puppetModules as $puppetModule): ?>
                    <tr>
                        <td class="module-name" style="width: 100%">
                            <?php echo $this->widget()->render('puppetModuleRowLeft', ['puppetModule' => $puppetModule]); ?>
                            <a href="<?php echo $this->url('puppet-module', ['action' => 'show', 'name' => $puppetModule->getName()], ['query' => ['back' => $this->url('puppet', ['controller' => 'modules', 'action' => 'index'], [], true)]], true) ?>" title="<?php echo $this->translate('View module') ?>"><span class="glyphicon glyphicon-search darkgrey" style="margin-right: 6px"></span><?php echo $puppetModule->getName() ?></a>
                        </td>
                        <td>
                            <span class="label <?php echo $this->puppetModuleLabelClass($puppetModule) ?>"><?php echo $puppetModule->getVersion() ?></span>
                            <?php echo $this->widget()->render('puppetModuleRowRight', ['puppetModule' => $puppetModule]); ?>
                        </td>
                    </tr>
                    <?php endforeach ?>
                    <?php endif ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-5">
        <h1><?php echo $this->translate('Help') ?></h1>
        <?php if (isset($this->environment)): ?>
        <blockquote>
            <p><?php echo sprintf($this->translate("Here is the list of installed modules on environment <strong>%s</strong>."), $this->environment->getNormalizedName()) ?></p>
            <p><?php echo $this->translate('When version of a module is red <span class="label label-danger">1.0.0</span>, it means that at least one of its classes is in error.') ?></p>
            <p><?php echo $this->translate('<strong>Note</strong> : The list of modules is refreshed every 5 minutes, but you can clear the cache manually by clicking on your name in the top right of the page.') ?></p>
        </blockquote>
        <?php endif ?>
    </div>
</div>
