<ul style="clear:both">
    <?php foreach ($this->parametersTemplates as $parameterTemplate): ?>
    <li>
        <span class="<?php if (array_key_exists($parameterTemplate->name, $this->errors)): echo 'bg-red'; endif ?>">
            <?php if (isset($parameterTemplate->entries)): ?>
            <i class="glyphicon glyphicon-minus-sign"></i>
            <?php endif ?>
            <i class="glyphicon glyphicon-zoom-<?php echo ( array_key_exists($parameterTemplate->name, $this->errors) ? 'out' : 'in' ) ?>"></i>
            <strong class="blue<?php if ($parameterTemplate->required): echo ' required'; endif ?>"><?php echo $parameterTemplate->name ?></strong>
            <dl class="dl-horizontal parameters"<?php if (!array_key_exists($parameterTemplate->name, $this->errors)): echo ' style="display: none"'; endif ?>>
                <dt><?php echo $this->translate('required') ?></dt>
                <dd><?php echo $this->printBoolean($parameterTemplate->required, \KmbBase\View\Helper\PrintBoolean::YES_NO) ?></dd>
                <dt><?php echo $this->translate('multiple values') ?></dt>
                <dd><?php echo $this->printBoolean($parameterTemplate->multiple_values, \KmbBase\View\Helper\PrintBoolean::YES_NO) ?></dd>
                <dt><?php echo $this->translate('type') ?></dt>
                <dd><?php echo $this->printParameterType($parameterTemplate->type) ?></dd>
                <?php if (isset($parameterTemplate->values)): ?>
                <dt><?php echo $this->translate('values') ?></dt>
                <?php foreach ($parameterTemplate->values as $value): ?>
                <dd class="value blue"><?php echo $value ?></dd>
                <?php endforeach ?>
                <?php endif ?>
                <?php if (array_key_exists($parameterTemplate->name, $this->errors)): ?>
                <dt class="red"><?php echo $this->translate('error') ?></dt>
                <dd class="red"><?php echo $this->errors[$parameterTemplate->name] ?></dd>
                <?php endif ?>
            </dl>
        </span>
        <?php if (isset($parameterTemplate->entries)): ?>
        <? echo $this->partial('kmb-puppet/modules/parameters-templates', ['parametersTemplates' => $parameterTemplate->entries]) ?>
        <?php endif ?>
    </li>
    <?php endforeach ?>
</ul>
