<ul style="clear:both">
    <?php foreach ($this->parametersTemplates as $parameterTemplate): ?>
    <li class="tree-level">
        <span class="tree-item <?php if (isset($this->errors) && array_key_exists($parameterTemplate->name, $this->errors)): echo 'bg-red'; endif ?>">
            <?php if (isset($parameterTemplate->entries)): ?>
            <a href="#"><i class="glyphicon glyphicon-minus-sign darkgrey"></i></a>
            <?php endif ?>
            <a href="#"><i class="glyphicon darkgrey glyphicon-zoom-<?php echo ( isset($this->errors) && array_key_exists($parameterTemplate->name, $this->errors) ? 'out' : 'in' ) ?>"></i></a>
            <strong class="blue<?php if ($parameterTemplate->required): echo ' required'; endif ?>"><?php echo $parameterTemplate->name ?></strong>
            <dl class="dl-horizontal see-more"<?php if (!isset($this->errors) || !array_key_exists($parameterTemplate->name, $this->errors)): echo ' style="display: none"'; endif ?>>
                <dt><?php echo $this->translate('required') ?></dt>
                <dd><?php echo $this->printBoolean(isset($parameterTemplate->required) ? $parameterTemplate->required : null, \KmbBase\View\Helper\PrintBoolean::YES_NO) ?></dd>
                <dt><?php echo $this->translate('multiple values') ?></dt>
                <dd><?php echo $this->printBoolean(isset($parameterTemplate->multiple_values) ? $parameterTemplate->multiple_values : null, \KmbBase\View\Helper\PrintBoolean::YES_NO) ?></dd>
                <dt><?php echo $this->translate('type') ?></dt>
                <dd><?php echo $this->printParameterType(isset($parameterTemplate->type) ? $parameterTemplate->type : null) ?></dd>
                <?php if (isset($parameterTemplate->values)): ?>
                <dt><?php echo $this->translate('values') ?></dt>
                <?php foreach ($parameterTemplate->values as $value): ?>
                <dd class="value blue"><?php echo $value ?></dd>
                <?php endforeach ?>
                <?php endif ?>
                <?php if (isset($this->errors) && array_key_exists($parameterTemplate->name, $this->errors)): ?>
                <dt class="red"><?php echo $this->translate('error') ?></dt>
                <dd class="red"><?php echo $this->errors[$parameterTemplate->name] ?></dd>
                <?php endif ?>
            </dl>
        </span>
        <?php if (isset($parameterTemplate->entries)): ?>
        <?php echo $this->partial('kmb-puppet/modules/parameters-templates', ['parametersTemplates' => $parameterTemplate->entries]) ?>
        <?php endif ?>
    </li>
    <?php endforeach ?>
</ul>
