<div class="row">
    <div class="row">
        <div class="col-md-12">
            <div><?php echo $this->translate('Detailed informations on class') ?></div>
            <div class="date"><?php echo $this->escapeHtml($this->class->getName()) ?></div>
        </div>
    </div>
    <div class="row">
        <?php if (isset($this->back)): ?>
            <div class="col-md-2 info-bar pull-left">
                <div class="grey"><span class="glyphicon glyphicon-chevron-left"></span></div>
                <div class="stats-title"><a href="<?php echo $this->escapeHtmlAttr($this->back) ?>" class="btn btn-info"><?php echo $this->translate('back') ?></a></div>
            </div>
        <?php endif ?>
    </div>
    <hr/>
    <div class="col-sm-6">
        <div class="panel panel-default" style="min-height: 370px">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span>
                    <?php echo sprintf($this->translate('Parameters of class %s'), $this->class->getName()) ?>
                </span>
            </div>
            <div class="panel-body">
                <?php if ($this->class->hasParametersTemplates()): ?>
                <div class="tree">
                    <div>
                        <a href="#" id="collapse-all" class="btn btn-default pull-right">
                            <span class="glyphicon glyphicon-minus-sign"></span>
                            <?php echo $this->translate('Collapse all') ?>
                        </a>
                        <a href="#" id="expand-all" class="btn btn-default pull-right" style="display:none">
                            <span class="glyphicon glyphicon-plus-sign"></span>
                            <?php echo $this->translate('Expand all') ?>
                        </a>
                    </div>
                    <?php echo $this->partial('kmb-puppet/modules/parameters-templates', ['parametersTemplates' => $this->class->getParametersTemplates(), 'errors' => $this->parametersErrors]) ?>
                </div>
                <?php else: ?>
                <h4><?php echo $this->translate('No parameters !') ?></h4>
                <?php endif ?>
                <p class="note pull-right"><strong class="red">*</strong> paramètre requis</p>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <?php echo $this->flashMessenger()->render('success', ['alert', 'alert-success']) ?>
        <?php echo $this->flashMessenger()->render('error', ['alert', 'alert-danger']) ?>
        <?php if (!empty($this->parametersErrors) || !empty($this->classErrors)): ?>
            <ul class="flash">
                <li class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <?php echo $this->translate("Parameters are in error, please check the template and the class definition") ?>
                </li>
                <?php foreach ($this->classErrors as $error): ?>
                    <li class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <?php echo $error ?>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endif ?>
        <h1><?php echo $this->translate('Documentation') ?></h1>
        <blockquote style="font-size: 1em; min-height: 300px">
        <?php if (isset($this->environment)): ?>
        <?php if ($this->class->getDocumentation() != ''): ?>
            <p><?php echo $this->markdownToHtml($this->class->getDocumentation()) ?></p>
        <?php else: ?>
            <p><?php echo $this->translate('Documention should be provided in the puppetdoc of the class.') ?></p>
        <?php endif ?>
        <?php endif ?>
        </blockquote>
    </div>
</div>
