<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.puppet.js'); ?>
<div class="row">
    <div class="col-sm-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span>
                    <?php echo $this->translate('Groups') ?>
                    <?php if (isset($this->environment) && $this->isGranted('manageEnv', $this->environment)): ?>
                    <?php if ($this->customGroups()->hasOnlyDefault()): ?>
                    <a class="btn btn-info btn-xs pull-right<?php if (!isset($this->groups)): ?> disabled<?php endif ?>" data-toggle="modal" data-target="#new-group" data-title="<?php echo $this->translate('Add a group') ?>" data-description="<?php echo $this->translate('A group allows to configure a set of Puppet classes and assigned them to a list of servers.') ?>" title="<?php echo $this->translate('Add a group') ?>">
                        <span class="glyphicon glyphicon-plus-sign"></span>
                        <?php echo $this->translate('Add') ?>
                    </a>
                    <?php else: ?>
                    <div class="btn-group pull-right">
                        <button type="button" class="btn btn-info btn-xs dropdown-toggle<?php if (!isset($this->groups)): ?> disabled<?php endif ?>" data-toggle="dropdown" aria-expanded="false">
                            <?php echo $this->translate('Add') ?> <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                        <?php foreach ($this->customGroups()->getConfig() as $type => $config): ?>
                            <li><a href="#" data-toggle="modal" data-target="#new-group" data-title="<?php echo $this->translate($config['label']) ?>" data-description="<?php echo $this->translate($config['description']) ?>" data-type="<?php echo $type ?>"><?php echo $this->translate($config['label']) ?></a></li>
                        <?php endforeach ?>
                        </ul>
                    </div>
                    <?php endif ?>
                    <?php endif ?>
                </span>
            </div>
            <div class="panel-body">
                <?php if (!empty($this->groups)): ?>
                <table class="table table-striped" id="groups">
                    <tbody>
                    <?php foreach ($this->groups as $group): ?>
                    <tr id="groups-<?php echo $group->getId() ?>">
                        <td class="module-name" style="width: 90%">
                            <span class="glyphicon glyphicon-th grab" title="<?php echo $this->translate('Sort groups') ?>"></span>
                            <?php if ($this->isGranted('manageEnv', $this->environment)): ?>
                            <a href="#" title="<?php echo $this->translate('Remove group') ?>" data-href="<?php echo $this->url('puppet-group', ['action' => 'remove', 'id' => $group->getId()], [], true) ?>" data-toggle="modal" data-target="#confirm-remove" data-confirm-param1="<?php echo sprintf($this->translate('You are about to remove <strong>%s</strong> group.'), $group->getName()) ?>"><i class="glyphicon glyphicon-remove red"></i></a>
                            <a href="#" title="<?php echo $this->translate('Duplicate group') ?>" data-href="<?php echo $this->url('puppet-group', ['action' => 'duplicate', 'id' => $group->getId()], [], true) ?>" data-group-name="<?php echo $group->getName() ?>" data-toggle="modal" data-target="#duplicate-group" data-confirm-param1="<?php echo sprintf($this->translate('You are about to duplicate <strong>%s</strong> group.'), $group->getName()) ?>"><i class="glyphicon glyphicon-duplicate grey"></i></a>
                            <?php endif ?>
                            <a href="<?php echo $this->url('puppet-group', ['action' => 'show', 'id' => $group->getId()], [], true) ?>" <?php if (isset($this->errors[$group->getName()])): ?>class="red"<?php endif ?> title="<?php echo $this->translate('View group') ?>"><span class="glyphicon glyphicon-search grey" style="margin-right: 6px"></span><?php echo $group->getName() ?></a>
                        </td>
                        <td class="text-right">
                            <?php if (isset($this->errors[$group->getName()])): ?>
                                <span class="label label-uniform label-danger">
                                    <?php echo $this->translate('Error') ?>
                                    <span class="badge alert-danger" data-rel="tooltip" data-placement="top" data-original-title="errors"><?php echo $this->errors[$group->getName()] ?></span>
                                </span>
                            <?php endif ?>
                        </td>
                    </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <?php else: ?>
                <p><?php echo $this->translate('No groups'); ?></p>
                <?php endif ?>
            </div>
        </div>
    </div>
    <div id="confirm-remove" class="modal fade confirm" tabindex="-1" role="dialog" aria-labelledby="confirmRemoveLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="confirmRemoveLabel"><?php echo $this->translate('Confirm Remove') ?></h1>
                </div>
                <div class="modal-body">
                    <blockquote>
                        <p class="confirm-param1"></p>
                        <p><?php echo $this->translate('Do you want to proceed ?') ?></p>
                    </blockquote>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                    <a href="#" class="btn btn-danger danger"><?php echo $this->translate('Remove') ?></a>
                </div>
            </div>
        </div>
    </div>
    <div id="duplicate-group" class="modal fade confirm" tabindex="-1" role="dialog" aria-labelledby="duplicateGroupLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="duplicateGroupLabel"><?php echo $this->translate('Duplicate a group') ?></h1>
                </div>
                <form role="form" action="" method="post">
                    <div class="modal-body">
                        <blockquote style="margin-top: 16px">
                            <p><?php echo $this->translate('You can duplicate a group in the current environment or in any other environment.') ?></p>
                        </blockquote>
                        <div class="form-group">
                            <label for="environment-select"><?php echo $this->translate('Select an environment') ?></label>
                            <select id="environment-select" class="form-control" name="targetEnvId" data-placeholder="<?php echo $this->translate('Select an environment') ?>" data-rel="chosen" style="display: none;">
                                <option></option>
                                <?php echo $this->environmentSelect('readEnv', true) ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="duplicate-group-name"><?php echo $this->translate('Choose a name') ?></label>
                            <input type="text" class="form-control" name="name" id="duplicate-group-name" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                        <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save') ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div id="new-group" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="newGroupLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="newGroupLabel"></h1>
                </div>
                <form role="form" action="<?php echo $this->url('puppet', ['controller' => 'groups', 'action' => 'create'], [], true) ?>" method="post">
                    <input type="hidden" name="type" value="" id="new-group-type" />
                    <div class="modal-body">
                        <blockquote style="margin-top: 16px" id="new-group-description">
                        </blockquote>
                        <div class="form-group">
                            <label for="create-group-name"><?php echo $this->translate('Choose a name') ?></label>
                            <input type="text" class="form-control" name="name" id="create-group-name" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                        <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save') ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-5">
        <h1><?php echo $this->translate('Help') ?></h1>
        <?php if (isset($this->environment)): ?>
        <blockquote>
            <p><?php echo sprintf($this->translate("Here is the list of groups on environment <strong>%s</strong>."), $this->environment->getNormalizedName()) ?></p>
            <p><?php echo $this->translate("You can see the details of a group by clicking on its name.") ?></p>
            <p><?php echo $this->translate("<strong>Caution</strong> : The order of groups is important ! When a server is associated to two groups which implements the same class, it's the class configuration of the lower group that will be sustained.") ?></p>
            <p><?php echo $this->translate("You can sort the groups by grabing the icon <span class=\"glyphicon glyphicon-th grab\"></span>.") ?></p>
        </blockquote>
        <?php endif ?>
    </div>
</div>
