<div class="row">
    <div class="col-sm-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span>
                    <?php echo $this->translate('Groups') ?>
                    <a class="btn btn-info btn-xs pull-right<?php if (!isset($this->groups)): ?> disabled<?php endif ?>">
                        <span class="glyphicon glyphicon-plus-sign"></span>
                        <?php echo $this->translate('Create a group') ?>
                    </a>
                </span>
            </div>
            <div class="panel-body">
                <?php if (!empty($this->groups)): ?>
                <table class="table table-striped" id="groups">
                    <tbody>
                    <?php foreach ($this->groups as $group): ?>
                    <tr id="groups-<?php echo $group->getId() ?>">
                        <td class="module-name" style="width: 100%">
                            <span class="glyphicon glyphicon-th grab"></span>
                            <span class="glyphicon glyphicon-search"></span>
                            <a href="<?php echo $this->url('puppet-group', ['action' => 'show', 'id' => $group->getId()], [], true) ?>"><?php echo $group->getName() ?></a>
                        </td>
                    </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <?php endif ?>
            </div>
        </div>
    </div>
    <div class="col-sm-5">
        <?php if (isset($this->error)): ?>
        <ul class="flash">
            <li class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <?php echo $this->error ?>
            </li>
        </ul>
        <?php endif ?>
        <?php echo $this->flashMessenger()->render('success', ['alert', 'alert-success']) ?>
        <?php echo $this->flashMessenger()->render('error', ['alert', 'alert-danger']) ?>
        <?php if (isset($this->environment)): ?>
        <h1><?php echo $this->translate('Help') ?></h1>
        <blockquote>
            <p><?php echo sprintf($this->translate("Here is the list of groups on environment <strong>%s</strong>."), $this->environment->getNormalizedName()) ?></p>
            <p><?php echo $this->translate("You can see the details of a group by clicking on its name.") ?></p>
            <p><?php echo $this->translate("<strong>Caution</strong> : The order of groups is important ! When a server is associated to two groups which implements the same class, it's the class configuration of the lower group that will be sustained.") ?></p>
            <p><?php echo $this->translate("You can sort the groups by grabing the icon <span class=\"glyphicon glyphicon-th grab\"></span>.") ?></p>
        </blockquote>
        <?php endif ?>
    </div>
</div>
