<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.puppet.js'); ?>
<div class="panel panel-default">
    <div class="panel-heading"><span class="glyphicon glyphicon-tasks"></span><span class="panel-break"></span><?php echo $this->translate('Day reports') ?></div>
    <div class="panel-body">
        <?php echo $this->datatable('reports_datatable')->renderHtml(); ?>
    </div>
</div>
