<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.puppet.js'); ?>
<div class="row">
    <div class="col-sm-9">
        <p>
            <a class="btn btn-info" href="<?php echo $this->url('puppet', ['controller' => 'environments', 'action' => 'index'], [], true) ?>">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <?php echo $this->translate('back') ?>
            </a>
        </p>
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#modules">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span><?php echo $this->translate('Installed modules') ?></span>
            </div>
            <div class="panel-body panel-collapse collapse in" id="modules">
                <?php if (!empty($this->modulesDiff)): ?>
                <?php echo $this->modulesDiff ?>
                <?php else: ?>
                <?php echo $this->translate('No differences') ?>
                <?php endif ?>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#groups-ordering">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span><?php echo $this->translate('Groups ordering') ?></span>
            </div>
            <div class="panel-body panel-collapse collapse in" id="groups-ordering">
                <?php if (!empty($this->groupsOrderingDiff)): ?>
                    <?php echo $this->groupsOrderingDiff ?>
                <?php else: ?>
                    <?php echo $this->translate('No differences') ?>
                <?php endif ?>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#groups-content">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span><?php echo $this->translate('Groups content') ?></span>
            </div>
            <div class="panel-body panel-collapse collapse in" id="groups-content">
            <?php if (!empty($this->groupsDiffs)): ?>
            <?php foreach ($this->groupsDiffs as $group => $diff): ?>
                <h5 class="DifferencesHeader"><?php echo sprintf($this->translate('Group %s'), $group) ?></h5>
                <?php echo $diff ?>
            <?php endforeach ?>
            <?php else: ?>
            <?php echo $this->translate('No differences') ?>
            <?php endif ?>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <h1><?php echo $this->translate('Help') ?></h1>
        <blockquote>
            <p><span class="DifferencesLegend ChangeInsert">&nbsp;</span>&nbsp;: <?php echo $this->translate('Insert') ?>.</p>
            <p><span class="DifferencesLegend ChangeReplace">&nbsp;</span>&nbsp;: <?php echo $this->translate('Replace') ?>.</p>
            <p><span class="DifferencesLegend ChangeDelete">&nbsp;</span>&nbsp;: <?php echo $this->translate('Delete') ?>.</p>
        </blockquote>
    </div>
</div>
