<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.puppet.js'); ?>
<div class="row">
    <div class="col-sm-9">
        <p>
            <a class="btn btn-info" href="<?php echo $this->url('puppet', ['controller' => 'environments', 'action' => 'index'], [], true) ?>">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <?php echo $this->translate('back') ?>
            </a>
        </p>
        <h3><?php echo $this->translate('Compare environments') ?></h3>
        <form class="" role="form" action="<?php echo $this->url('puppet', ['controller' => 'environments', 'action' => 'diff'], [], true) ?>" method="get">
        <table style="width: 100%">
            <thead>
                <tr>
                    <td style="width: 45%; padding: 10px 10px 20px 0">
                        <select class="form-control" name="from" data-rel="chosen" style="display: none;">
                            <?php echo $this->environmentSelect('readEnv', $this->from->getId()) ?>
                        </select>
                    </td>
                    <td style="width: 45%; padding: 10px 10px 20px">
                        <select class="form-control" name="to" data-rel="chosen" style="display: none;">
                            <?php echo $this->environmentSelect('readEnv', $this->to->getId()) ?>
                        </select>
                    </td>
                    <td style="width: 10%; padding: 10px 0 20px 10px">
                        <button class="btn btn-grey" title="<?php echo $this->translate('Compare environments') ?>">
                            <span class="glyphicon glyphicon-transfer"></span>
                            <?php echo $this->translate('Compare') ?>
                        </button>
                    </td>
                </tr>
            </thead>
        </table>
        </form>
        <div class="panel panel-default" style="clear: left">
            <div class="panel-heading" data-toggle="collapse" data-target="#modules">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span><?php echo $this->translate('Installed modules') ?></span>
            </div>
            <div class="panel-body panel-collapse collapse in" id="modules">
                <?php if (!empty($this->modulesDiff)): ?>
                <?php echo $this->modulesDiff ?>
                <?php else: ?>
                <?php echo $this->translate('No differences') ?>
                <?php endif ?>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#groups-ordering">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span><?php echo $this->translate('Groups ordering') ?></span>
            </div>
            <div class="panel-body panel-collapse collapse in" id="groups-ordering">
                <?php if (!empty($this->groupsOrderingDiff)): ?>
                    <?php echo $this->groupsOrderingDiff ?>
                <?php else: ?>
                    <?php echo $this->translate('No differences') ?>
                <?php endif ?>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#groups-content">
                <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
                <span><?php echo $this->translate('Groups content') ?></span>
            </div>
            <div class="panel-body panel-collapse collapse in" id="groups-content">
            <?php if (!empty($this->groupsDiffs)): ?>
            <?php foreach ($this->groupsDiffs as $group => $diff): ?>
                <h5 class="DifferencesHeader"><?php echo sprintf($this->translate('Group %s'), $group) ?></h5>
                <?php echo $diff ?>
            <?php endforeach ?>
            <?php else: ?>
            <?php echo $this->translate('No differences') ?>
            <?php endif ?>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <h1><?php echo $this->translate('Help') ?></h1>
        <blockquote>
            <p><span class="DifferencesLegend ChangeInsert">&nbsp;</span>&nbsp;: <?php echo $this->translate('Insert') ?>.</p>
            <p><span class="DifferencesLegend ChangeReplace">&nbsp;</span>&nbsp;: <?php echo $this->translate('Replace') ?>.</p>
            <p><span class="DifferencesLegend ChangeDelete">&nbsp;</span>&nbsp;: <?php echo $this->translate('Delete') ?>.</p>
        </blockquote>
    </div>
</div>
