<ul>
    <?php foreach ($this->environments as $environment): ?>
        <li>
        <?php if ($environment->hasChildren()): ?>
            <span>
                <i class="glyphicon glyphicon-minus-sign"></i>
                <?php if ($this->isGranted('manageEnvChildren', $environment)): ?>
                <a href="#" data-toggle="modal" data-target="#create-environment" data-parent-id="<?php echo $environment->getId() ?>"><i class="glyphicon glyphicon-plus icon-blue"></i></a>
                <?php endif ?>
                <?php if ($this->isGranted('manageEnv', $environment)): ?>
                <a href="#" data-href="<?php echo $this->url('puppet/withid', ['controller' => 'environments', 'action' => 'update', 'id' => $environment->getId()]) ?>" data-toggle="modal" data-target="#update-environment" data-name="<?php echo $environment->getName() ?>" data-full-name="<?php echo $this->formatAncestorsNames($environment) ?>"  data-id="<?php echo $environment->getId() ?>" data-parent-id="<?php echo $environment->hasParent() ? $environment->getParent()->getId() : 0 ?>"><i class="glyphicon glyphicon-pencil icon-grey"></i></a>
                <?php endif ?>
                <?php echo $environment->getName() ?>
            </span>
            <? echo $this->partial('kmb-puppet/environments/environments', ['environments' => $environment->getChildren()]) ?>
        <?php else: ?>
            <span>
                <?php if ($this->isGranted('manageEnvChildren', $environment)): ?>
                <a href="#" data-toggle="modal" data-target="#create-environment" data-parent-id="<?php echo $environment->getId() ?>"><i class="glyphicon glyphicon-plus icon-blue"></i></a>
                <?php endif ?>
                <?php if ($this->isGranted('manageEnv', $environment)): ?>
                <a href="#" data-href="<?php echo $this->url('puppet/withid', ['controller' => 'environments', 'action' => 'remove', 'id' => $environment->getId()]) ?>" data-toggle="modal" data-target="#confirm-remove" data-confirm-param1="<?php echo $environment->getName() ?>"><i class="glyphicon glyphicon-remove icon-red"></i></a>
                <a href="#" data-href="<?php echo $this->url('puppet/withid', ['controller' => 'environments', 'action' => 'update', 'id' => $environment->getId()]) ?>" data-toggle="modal" data-target="#update-environment" data-name="<?php echo $environment->getName() ?>" data-full-name="<?php echo $this->formatAncestorsNames($environment) ?>" data-id="<?php echo $environment->getId() ?>" data-parent-id="<?php echo $environment->hasParent() ? $environment->getParent()->getId() : 0 ?>"><i class="glyphicon glyphicon-pencil icon-grey"></i></a>
                <?php endif ?>
                <?php echo $environment->getName() ?>
            </span>
        <?php endif ?>
        </li>
    <?php endforeach ?>
</ul>
