<div class="row">
    <div id="confirm-remove" class="modal fade confirm" tabindex="-1" role="dialog" aria-labelledby="confirmRemoveLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="confirmRemoveLabel"><?php echo $this->translate('Confirm Remove') ?></h1>
                </div>
                <div class="modal-body">
                    <blockquote>
                        <p><?php echo sprintf($this->translate('You are about to remove %s environment, this procedure is irreversible.'), '<strong class="confirm-param1"></strong>') ?></p>
                        <p><?php echo $this->translate('Do you want to proceed ?') ?></p>
                    </blockquote>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                    <a href="#" class="btn btn-danger danger"><?php echo $this->translate('Remove') ?></a>
                </div>
            </div>
        </div>
    </div>
    <div id="create-environment" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createEnvironmentLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="createEnvironmentLabel"><?php echo $this->translate('Create an environment') ?></h1>
                </div>
                <form class="" role="form" action="<?php echo $this->url('puppet', ['controller' => 'environments', 'action' => 'create'], [], true) ?>" method="post">
                    <div class="modal-body" style="min-height: 420px">
                        <blockquote style="margin-top: 16px">
                            <p><?php echo $this->translate('You have to choose a parent and a name for this environment.') ?></p>
                            <p><?php echo $this->translate('The environment will automatically inherits of all the modules (in the same version) presents in each of its ancestors.') ?></p>
                        </blockquote>
                        <div class="form-group">
                            <label for="create-parent-select"><?php echo $this->translate('Select a parent') ?></label>
                            <select id="create-parent-select" class="form-control" name="parent" data-placeholder="<?php echo $this->translate('Select an environment') ?>" data-rel="chosen" style="display: none;">
                                <option></option>
                                <?php if ($this->hasRole(\KmbDomain\Model\UserInterface::ROLE_ROOT)): ?>
                                <option value="0">&minus;</option>
                                <?php endif ?>
                                <?php echo $this->environmentSelect() ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="create-environment-name"><?php echo $this->translate('Choose a name') ?></label>
                            <p><?php echo $this->translate('The name must be <strong>alphanumeric</strong> only ! All special characters are forbidden (including underscore).') ?></p>
                            <input type="text" class="form-control" name="name" id="create-environment-name" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                        <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save') ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div id="update-environment" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="updateEnvironmentLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="updateEnvironmentLabel"><?php echo $this->translate('Update an environment') ?></h1>
                    <h4 class="lightgrey" id="current-environment-name"></h4>
                </div>
                <form class="" role="form" action="" method="post">
                    <div class="modal-body" style="min-height: 420px">
                        <blockquote>
                            <p><strong><?php echo $this->translate('REMINDER') ?></strong> : <?php echo $this->translate('The environment will automatically inherits of all the modules (in the same version) presents in each of its ancestors.') ?></p>
                        </blockquote>
                        <div class="form-group">
                            <label for="update-parent-select"><?php echo $this->translate('Select a parent') ?></label>
                            <select id="update-parent-select" class="form-control" name="parent" data-placeholder="<?php echo $this->translate('Select an environment') ?>" data-rel="chosen" style="display: none;">
                                <option></option>
                                <?php if ($this->hasRole(\KmbDomain\Model\UserInterface::ROLE_ROOT)): ?>
                                <option value="0">&minus;</option>
                                <?php endif ?>
                                <?php echo $this->environmentSelect() ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="update-environment-name"><?php echo $this->translate('Choose a name') ?></label>
                            <p><?php echo $this->translate('The name must be <strong>alphanumeric</strong> only ! All special characters are forbidden (including underscore).') ?></p>
                            <input type="text" class="form-control" name="name" id="update-environment-name" />
                        </div>
                        <?php if ($this->hasRole(\KmbDomain\Model\UserInterface::ROLE_ROOT)): ?>
                        <div class="form-group">
                            <label for="update-environment-default">
                                <?php echo $this->translate('Default environment') ?>
                            </label>
                            <p><?php echo $this->translate('All servers which has not already been assigned to an environment will be automatically assigned to the default environment.') ?></p>
                            <label>
                                <input type="checkbox" name="default" id="update-environment-default" />
                                <?php echo $this->translate('Mark this environment as default') ?>
                            </label>
                        </div>
                        <?php endif ?>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                        <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save') ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div id="manage-environment-users" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="manageEnvironmentUsersLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="manageEnvironmentUsersLabel"><?php echo $this->translate('Manage permissions') ?></h1>
                    <h4 class="lightgrey" id="current-environment-name"></h4>
                </div>
                <div class="modal-body" style="min-height: 420px">
                    <blockquote>
                        <p>
                            <?php echo $this->translate('A <strong>user</strong> can read his environments, their ancestors and children.') ?>
                            <?php echo $this->translate('An <strong>admin</strong> can read his environments and their ancestors, and manage their children.') ?>
                        </p>
                    </blockquote>
                    <div class="form-group">
                        <div class="input-group">
                            <select id="environment-user-select" class="form-control" name="users[]" multiple="multiple" data-placeholder="<?php echo $this->translate('Select users') ?>" data-rel="chosen" style="display: none;">
                                <option></option>
                            </select>
                            <div class="input-group-btn">
                                <button class="btn btn-info" type="submit" id="add-users" data-environment-id=""><i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Add') ?></button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <table class="table table-striped table-hover table-condensed bootstrap-datatable datatable" id="environment-users">
                            <thead>
                            <tr>
                                <th><?php echo $this->translate('Login') ?></th>
                                <th><?php echo $this->translate('Name') ?></th>
                                <th><?php echo $this->translate('Role') ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-cog"></span>
                <span class="panel-break"></span>
                <?php echo $this->translate('Environments') ?>
                <?php if ($this->hasRole(\KmbDomain\Model\UserInterface::ROLE_ROOT)): ?>
                <a href="#" class="btn btn-info btn-xs pull-right" data-toggle="modal" data-target="#create-environment" data-parent-id="0">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?php echo $this->translate('Create an environment') ?>
                </a>
                <?php endif ?>
            </div>
            <div class="panel-body">
                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $this->translate('Search') ?>" name="search">
                        <div class="input-group-btn">
                            <button class="btn btn-default disabled" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </form>
                <div class="tree">
                    <a href="#" class="btn btn-default collapse-all pull-right">
                        <span class="glyphicon glyphicon-minus-sign"></span>
                        <?php echo $this->translate('Collapse all') ?>
                    </a>
                    <a href="#" class="btn btn-default expand-all pull-right" style="display:none">
                        <span class="glyphicon glyphicon-plus-sign"></span>
                        <?php echo $this->translate('Expand all') ?>
                    </a>
                    <?php echo $this->partial('kmb-puppet/environments/environments', ['environments' => $this->environments]) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-5">
        <?php if (isset($this->message)): ?>
        <ul class="flash">
            <li class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <?php echo $this->message ?>
            </li>
        </ul>
        <?php endif ?>
        <?php echo $this->flashMessenger()->render('success', ['alert', 'alert-success']) ?>
        <?php echo $this->flashMessenger()->render('error', ['alert', 'alert-danger']) ?>
        <h1><?php echo $this->translate('Help') ?></h1>
        <blockquote>
            <p>
                <?php echo sprintf($this->translate("Filter the list by typing your terms in the search field, then click on the button %s."), '<i class="glyphicon glyphicon-search"></i>') ?>
            </p>
            <p>
                <?php echo sprintf($this->translate("You can expand / collapse the children of each environment by clicking on the buttons %s."), '<i class="glyphicon glyphicon-plus-sign"></i> <i class="glyphicon glyphicon-minus-sign"></i>') ?>
            </p>
            <?php if ($this->hasRole(\KmbDomain\Model\UserInterface::ROLE_ADMIN)): ?>
            <p>
                <?php echo sprintf($this->translate("Click on %s to add a child to the environment."), '<i class="glyphicon glyphicon-plus lightblue"></i>') ?>
            </p>
            <p>
                <?php echo sprintf($this->translate("Remove the environment by clicking on %s."), '<i class="glyphicon glyphicon-remove red"></i>') ?>
            </p>
            <p>
                <?php echo sprintf($this->translate("Click on %s to update the name and/or the parent of the environment."), '<i class="glyphicon glyphicon-pencil darkgrey"></i>') ?>
            </p>
            <p>
                <?php echo sprintf($this->translate("Manage permissions by clicking on %s."), '<i class="glyphicon glyphicon-user darkgrey"></i>') ?>
            </p>
            <?php endif ?>
        </blockquote>
    </div>
</div>
