<div class="row">
    <div class="col-sm-7">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-cog"></span><span
                    class="panel-break"></span><?php echo $this->translate('Environments') ?><a class="btn btn-info btn-xs pull-right"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp;<?php echo $this->translate('Create an environment') ?></a></div>
            <div class="panel-body">
                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $this->translate('Search') ?>" name="search">
                        <div class="input-group-btn">
                            <button class="btn btn-default disabled" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </form>
                <div class="tree ">
                    <?php echo $this->partial('kmb-puppet/environments/environments', ['environments' => $this->environments]) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-5">
        <h1>Aide</h1>
        <blockquote>
            <p>
                <?php echo sprintf($this->translate("Filter the list by typing your terms in the search field, then click on the button %s."), '<i class="glyphicon glyphicon-search"></i>') ?>
            </p>
            <p>
                <?php echo sprintf($this->translate("You can expand / collapse the children of each environment by clicking on the buttons %s."), '<i class="glyphicon glyphicon-plus-sign"></i> <i class="glyphicon glyphicon-minus-sign"></i>') ?>
            </p>
            <p>
                <?php echo sprintf($this->translate("View the detail of an environment by clicking on its name or on the associated button %s."), '<i class="glyphicon glyphicon-zoom-in"></i>') ?>
            </p>
        </blockquote>
    </div>
</div>